services:
  - type: web
    name: obyavka-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: obyavka-db
          property: connectionString

databases:
  - name: obyavka-db
    plan: free
    postgresMajorVersion: 15